package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'SecondComposite'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("SecondComposite")) {
    dependencies {
        expect(RelativeId("ParentComposite")) {
            snapshot {
                onDependencyCancel = FailureAction.ADD_PROBLEM
            }
        }
        update(RelativeId("ParentComposite")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }

    }
}
